name: My practice task 1
on: push
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: Install dependency
        run: npm install
      - name: Fix linting
        run: npm run lint
      - name: Build project
        run: npm run build
      - name: Test project
        run: npm run test